version: '3.8'

services:
  pokerbot:
    container_name: pokerbot
    build:
      context: .
      dockerfile: Dockerfile
    image: poker-chatbot
    env_file:
      - .env
    ports:
      - 3000:3000
    working_dir: /pokerbot
    volumes:
      - .:/pokerbot
      - node_modules:/pokerbot/node_modules

volumes:
  node_modules:
